var pikachuHP= 35;
var pikachuNum= 025;
var pikachuType= "Eletric";
var pikachuBestMove= "Wild Charge";
var pikachuLastEvo= false;
var pikachuAttack= 55;
var pikachuDefense= 40;
var pikachuSpeed= 90;
var pikachuSpecies= "MousenPokemon";
var pikachuWeight= 13.2;
console.log(pikachuHP);
console.log(pikachuNum);
console.log(pikachuType);
console.log(pikachuBestMove);
console.log(pikachuLastEvo);
console.log(pikachuAttack);
console.log(pikachuDefense);
console.log(pikachuSpeed);
console.log(pikachuSpecies);
console.log(pikachuWeight);